spring:
  application:
    name: login

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    springfox.documentation: INFO
    io.swagger: INFO